[2024-09-24 10:24:41,585] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 10:24:43,425] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 10:24:43,427] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 10:24:49,374] INFO _log() L96   127.0.0.1 - - [24/Sep/2024 10:24:49] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 10:25:01,050] INFO _log() L96   127.0.0.1 - - [24/Sep/2024 10:25:01] "DELETE /paciente?name=Jhansen HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 10:25:04,228] WARNING get_pacientes() L36   Não há pacientes cadastrados no banco de dados :/ - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\MVP 3\app_classifica_problema_cardiaco_api\app.py L36  
[2024-09-24 10:25:04,230] INFO _log() L96   127.0.0.1 - - [24/Sep/2024 10:25:04] "[33mGET /pacientes HTTP/1.1[0m" 404 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 17:02:59,223] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 17:02:59,223] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 17:02:59,242] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 17:03:01,814] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 17:03:01,816] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 17:03:01,837] WARNING get_pacientes() L36   Não há pacientes cadastrados no banco de dados :/ - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\MVP 3\app_classifica_problema_cardiaco_api\app.py L36  
[2024-09-24 17:03:01,838] INFO _log() L96   127.0.0.1 - - [24/Sep/2024 17:03:01] "[33mGET /pacientes HTTP/1.1[0m" 404 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 17:03:05,904] WARNING get_pacientes() L36   Não há pacientes cadastrados no banco de dados :/ - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\MVP 3\app_classifica_problema_cardiaco_api\app.py L36  
[2024-09-24 17:03:05,905] INFO _log() L96   127.0.0.1 - - [24/Sep/2024 17:03:05] "[33mGET /pacientes HTTP/1.1[0m" 404 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:09:52,001] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:09:52,002] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:09:52,034] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:09:55,255] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:09:55,320] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:10:06,187] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\streamlit\\env_util.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:10:06,188] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\streamlit\\delta_generator.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:10:06,189] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\streamlit\\elements\\heading.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:10:06,190] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\streamlit\\runtime\\metrics_util.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:10:06,191] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\streamlit\\runtime\\scriptrunner\\script_runner.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:10:06,192] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\streamlit\\runtime\\scriptrunner\\exec_code.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:10:06,194] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:10:06,866] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:10:13,504] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:10:13,507] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:11:06,095] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sklearn\\base.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:11:06,131] INFO _log() L96   127.0.0.1 - - [24/Sep/2024 20:11:06] "POST /paciente HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:11:07,096] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:11:10,287] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:11:10,291] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:11:23,440] INFO _log() L96   127.0.0.1 - - [24/Sep/2024 20:11:23] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:11:42,699] INFO _log() L96   127.0.0.1 - - [24/Sep/2024 20:11:42] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:12:18,910] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:12:18,911] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:12:18,928] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:12:22,363] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 20:12:22,366] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
