[2024-09-23 23:33:11,910] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:33:14,042] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:33:14,045] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:33:14,430] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\OneDrive\\Área de Trabalho\\MVP\\app_classifica_problema_cardiaco_api\\app.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:33:14,432] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\OneDrive\\Área de Trabalho\\MVP\\app_classifica_problema_cardiaco_api\\app.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:33:15,329] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:33:17,443] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:33:17,446] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:40:31,390] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:40:31,391] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:40:31,400] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:40:33,335] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:40:33,337] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:40:40,398] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:40:40] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:41:01,633] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:41:01] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:41:01,661] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:41:01] "DELETE /paciente?name=João HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:41:11,071] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:41:11] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:04,310] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:04] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:05,724] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:05] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:05,748] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:05] "DELETE /paciente?name=Maria HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:05,755] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:05] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:16,516] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:16] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:19,411] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:19] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:19,447] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:19] "DELETE /paciente?name=koelho HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:19,454] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:19] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:20,381] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:20] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:20,412] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:20] "DELETE /paciente?name=teste+44 HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:20,419] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:20] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:21,841] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:21] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:23,600] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:23] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:23,633] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:23] "DELETE /paciente?name=jhjhjhj HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:23,643] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:23] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:25,011] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:25] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:25,030] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:25] "DELETE /paciente?name=novo+paciente HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:43:25,038] WARNING get_pacientes() L36   Não há pacientes cadastrados no banco de dados :/ - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\MVP\app_classifica_problema_cardiaco_api\app.py L36  
[2024-09-23 23:43:25,039] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:43:25] "[33mGET /pacientes HTTP/1.1[0m" 404 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:49:43,397] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\streamlit\\runtime\\state\\session_state_proxy.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:49:44,360] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:49:47,247] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:49:47,249] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:49:51,446] WARNING get_pacientes() L36   Não há pacientes cadastrados no banco de dados :/ - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\MVP\app_classifica_problema_cardiaco_api\app.py L36  
[2024-09-23 23:49:51,447] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:49:51] "[33mGET /pacientes HTTP/1.1[0m" 404 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:50:07,871] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:50:07] "[31m[1mPOST /paciente HTTP/1.1[0m" 422 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 23:52:29,604] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 23:52:29] "POST /paciente HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
